In [2]:
import yfinance as yf

In [30]:
data = yf.download(  # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = "KO",

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
        period = "max",

#         start = "2000-01-1",
#         end = "2020-12-31",
    
        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "1d",

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'ticker',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = False,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = True,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None
    )

[*********************100%***********************]  1 of 1 completed

In [31]:
data

                 Open       High        Low      Close  Adj Close    Volume
Date
1962-01-02   0.263021   0.270182   0.263021   0.263021   0.051133    806400
1962-01-03   0.259115   0.259115   0.253255   0.257161   0.049994   1574400
1962-01-04   0.257813   0.261068   0.257813   0.259115   0.050374    844800
1962-01-05   0.259115   0.262370   0.252604   0.253255   0.049234   1420800
1962-01-08   0.251302   0.251302   0.245768   0.250651   0.048728   2035200
...               ...        ...        ...        ...        ...       ...
2021-11-26  54.590000  54.750000  53.580002  53.730000  53.316540  14754300
2021-11-29  54.049999  54.730000  53.930000  54.580002  54.160000  22712500
2021-11-30  53.599998  53.630001  52.439999  52.450001  52.450001  30485200
2021-12-01  52.980000  53.520000  52.279999  52.299999  52.299999  18719600
2021-12-02  52.599998  53.340000  52.505001  53.070000  53.070000  16971853

[15085 rows x 6 columns]

In [49]:
data1 = yf.download(  # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = "KO",

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
#         period = "max",

        start = "2021-10-06",
        end = "2021-12-04",
    
        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "2m",

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'ticker',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = False,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = True,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None
    )

[*********************100%***********************]  1 of 1 completed

In [50]:
data1

                            Open   High    Low  Close  Adj Close  Volume
Datetime
2021-10-22 04:00:00-04:00  54.38  54.38  54.35  54.36      54.36       0
2021-10-22 04:02:00-04:00  54.37  54.40  54.37  54.37      54.37       0
2021-10-22 04:04:00-04:00  54.37  54.38  54.37  54.37      54.37       0
2021-10-22 04:06:00-04:00  54.38  54.38  54.37  54.37      54.37       0
2021-10-22 04:08:00-04:00  54.42  54.42  54.37  54.40      54.40       0
...                          ...    ...    ...    ...        ...     ...
2021-12-03 19:40:00-05:00  53.54  53.55  53.54  53.55      53.55       0
2021-12-03 19:46:00-05:00  53.63  53.64  53.59  53.59      53.59       0
2021-12-03 19:48:00-05:00  53.64  53.64  53.64  53.64      53.64       0
2021-12-03 19:52:00-05:00  53.54  53.54  53.54  53.54      53.54       0
2021-12-03 19:58:00-05:00  53.63  53.63  53.63  53.63      53.63       0

[12437 rows x 6 columns]